### ISSUE TITLE
Add .editorconfig

### ISSUE THREAD

**Issue by AndreVarandas** [AndreVarandas/the-flappy-bird#13]
We need an .editorconfig file that should be placed at the root of the project and can be something like the following:

```
# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true

# 2 space indentation
[*.{js,json}]
indent_style = space
indent_size = 2

```

**Comment by AndreVarandas** [comment]
Hi 👋 @aakankasha028 ! Sure thing! Thank you!

**Comment by aakankasha028** [comment]
@AndreVarandas I have added the .editorconfig file but while pushing through a new branch am getting 
remote: Permission to AndreVarandas/the-flappy-bird.git denied to aakankasha028.
fatal: unable to access 'https://github.com/AndreVarandas/the-flappy-bird/': The requested URL returned error: 403

**Comment by AndreVarandas** [comment]
did you fork + new branch inside the fork? GitHub should suggest the PR to our repository afterwards 😊

**Comment by aakankasha028** [comment]
Okay :) I will do the same. Thanks for the info!!!
