### ISSUE TITLE
docs: logo

### ISSUE THREAD

**Issue by AndreVarandas** [AndreVarandas/the-flappy-bird#2]
We need an awesome logo! Please use your imagination 😎 

- Create a new folder named `extra`.
- Add the logo to the `extra` folder.
- Update our `readme.md` to include your logo (should be included at the very top of the document)

PR must be made against the `develop` branch.

**Comment by flipps** [comment]
Hey, hello Andre! I would like to go and try to help with that! :)

**Comment by AndreVarandas** [comment]
Thank you @flipps ! I am assigning this issue to you 👍

**Comment by AndreVarandas** [comment]
#9 was accepted, but we can also use another logo to use in game! 👍

**Comment by flipps** [comment]
@Daibushi really enjoyed your logo :) congratz!

**Comment by Daibushi** [comment]
Thanks guy. @flipps

**Comment by AndreVarandas** [comment]
Thanks everyone! 👍
