### ISSUE TITLE
Create new sprite for the blue bird

### ISSUE THREAD

**Issue by AndreVarandas** [AndreVarandas/the-flappy-bird#27]
We need a new sprite like it was done for https://github.com/AndreVarandas/the-flappy-bird/blob/develop/src/assets/sprites/yellowbird.png.

This can be easily done in https://www.piskelapp.com/ - by importing the downflap, middleflap and upflap blue bird assets and displaying them vertically.

The new asset should be named bluebird.png

**Comment by Haltz01** [comment]
I've looked at it and now it's done! Hope it's good enough.

**Comment by AndreVarandas** [comment]
It's perfect! Thank you @Haltz01 ! Closed with #28
